# Configuration file for YOLOv2 Darknet19 in COCO dataset

####################
# Common params    #
####################
anchors  : [[0.03014368, 0.03565184], [0.09865579, 0.10855421], [0.17570684, 0.28812316], [0.41488526, 0.18567263], [0.51423789, 0.48254105]]
label_map: './dataset/coco/categories.txt'

########################
# Model configuration  #
########################
model:
  name:          yolov2_darknet
  image_size:    320
  num_classes:   80
  num_anchors:   5
  shrink_factor: 32
  weight_file:   yolo-coco.weights

##########################
# Train Hyper-parameters #
##########################
training_params:
  epochs:          50
  batch_size:      32
  steps_per_epoch: 1000
  learning_rate:   0.00001
  backup_dir:      ./backup   # store best trained model and logs for tensorboard

#########################
# Deployment Parameters #
#########################
deploy_params:
  output_path:      /tmp/     # it will generate a directory using model[name] (/tmp/yolov2_darknet)
  version:          1         # a TF Serving may have multiple versions
  maximum_boxes:    100
  iou_threshold:    0.5
  score_threshold:  0.0

###########################
# inference Parameters #
###########################
inference:
  server:          localhost:9000
  frame_width:     480
  frame_height:    640
  frame_fps:       60
  score_threshold: 0.7

